export { default as AllPages } from "./AllPages"
export { default as Home } from "./Home"
export { default as Category } from "./Category"
export { default as Details } from "./Details"
export { default as Cart } from "./Cart"